config/routes.rb
Rails.application.routes.draw do
  delete '/articles/delete',          to: 'articles#destroy_selected', constraints: { only_ajax: true }
  post   '/articles/half-size-state', to: 'articles#half_size_state',  constraints: { active: true|false, only_ajax: true }

  resources 'articles', only: [:index, :destroy]

  get '/settings',   to: 'settings#index'
  get '/statistics', to: 'statistics#index'

  scope '/admin' do
    resources 'categories' do
      resources 'tags'
    end
  end

  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="row">
    <div class="col-xs-12">
      <div class="collapse" id="collapsing-navbar">
        <div class="p-a">
          <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to t(:articles),   articles_path,   class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to t(:settings),   settings_path,   class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to t(:statistics), statistics_path, class: 'nav-link' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-sm-3">
      <%= link_to 'Harpoon', root_path, class: 'navbar-brand' %>
    </div>

    <div class="col-sm-6 hidden-xs-down">
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to t(:articles),   articles_path,   class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to t(:settings),   settings_path,   class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to t(:statistics), statistics_path, class: 'nav-link' %></li>
      </ul>
    </div>

    <div class="col-sm-2 hidden-xs-down">
      <form class="form-inline navbar-form pull-right">
        <input type="text" class="form-control" placeholder="<%= t :search %>">
      </form>
    </div>

    <div class="col-xs-2 hidden-sm-up">
      <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#collapsing-navbar">
        &#9776;
      </button>
    </div>
  </div>
</nav>